# Site settings
title: Robert Chang's Personal Website 
email: robert8138@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  This is Robert Chang's personal website, powered by Jekyll, hosted on Github
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _rchang
github_username: robert8138
medium_username: rchang
quora_username: Robert-Chang-1
linkedin_username: robert-chang

# Build settings
markdown: kramdown
