# Site settings
title: Robert Chang's Blog
email: robert8138@gmail.com
description: "This is Robert Chang's personal website, powered by Jekyll, hosted on Github"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://robert8138.github.io" # the base hostname & protocol for your site
twitter_username: _rchang
github_username: robert8138
linkedin_username: robert-ih-chang

# Build settings
markdown: kramdown
